services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=DevelopmentPassword.2025
    ports:
      - 1433:1433
  # TODO: setup redis authentication
  redis:
    image: redis:7.4.2
  adminer:
    image: adminer
    ports:
      - 8080:8080
