services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: ["npm", "run", "dev:https"]
    volumes:
      - frontend-sync:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://localhost:8080/api
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - backend-sync:/app
    environment:
      - CA_OIDC_GOOGLE_AUTHORITY=https://accounts.google.com
      - CA_MSSQL_HOST=db,1433
      - CA_MSSQL_PASSWORD=DevelopmentPassword.2025
      - CA_FRONTEND_URL=https://frontend:3000
    ports:
      - 8080:8080

  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=DevelopmentPassword.2025
    ports:
      - 1433:1433
  # TODO: setup redis authentication
  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  backend-sync:
    external: true
  frontend-sync:
    external: true
